version: "3"

services:
  code:
    image: typhoon-front
    container_name: typhoon_front
    restart: always
    environment:
      - VIRTUAL_HOST=typhoon.viarezo.fr
      - LETSENCRYPT_HOST=typhoon.viarezo.fr
      - LETSENCRYPT_EMAIL=benjamin.koltes@student.ecp.fr

networks:
  default:
    external:
      name: nginx-proxy
