version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  code:
    build: .
    volumes:
      - .:/go/src/app
    # command: go run server.go
    command: watcher server.go
    working_dir: /go/src/app
    environment:
      - PORT=3000
      - VIRTUAL_HOST=typhoon-dev.viarezo.fr
    ports:
      - "3000:80"
    expose:
      - "3000"
    stdin_open: true
    tty: true
