version: "3"

services:
  nginx:
    image: nginx
    container_name: proxy_to_host
    restart: always
    environment:
      - VIRTUAL_HOST=typhoon-back.typhoon.viarezo.fr
      - LETSENCRYPT_HOST=typhoon-back.typhoon.viarezo.fr
      - LETSENCRYPT_EMAIL=aymeric.bernard@student.ecp.fr
    volumes:
      - /home/debian/typhoon/proxy-to-host/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    external:
      name: nginx-proxy
